version: '2'
services:
  spark-master:
    image: bde2020/spark-master:2.4.1-hadoop2.7
    mem_limit: 2G
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       - /mnt/spark-apps:/opt/spark-apps
       - /mnt/spark-data:/opt/spark-data
  spark-worker-1:
    image: bde2020/spark-worker:2.4.1-hadoop2.7
    mem_limit: 2G
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.3
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
       - /mnt/spark-apps:/opt/spark-apps
       - /mnt/spark-data:/opt/spark-data  
  spark-worker-2:
    image: bde2020/spark-worker:2.4.1-hadoop2.7
    mem_limit: 2G
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.4
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
       - /mnt/spark-apps:/opt/spark-apps
       - /mnt/spark-data:/opt/spark-data 
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
